
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["PGHOST"] %>
  database: <%= ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  timeout: 5000

development:
  <<: *default
  database: try_deploy_to_aws_development

test:
  <<: *default
  database: try_deploy_to_aws_test

production:
  primary: &primary_production
    <<: *default
    database: try-deploy-to-aws-production-prod
