
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>
  timeout: 5000

development:
  <<: *default
  database: try_deploy_to_aws_development

test:
  <<: *default
  database: try_deploy_to_aws_test

production:
  primary: &primary_production
    <<: *default
    database: try_deploy_to_aws_production
    username: try_deploy_to_aws
    password: <%= ENV["TRY_DEPLOY_TO_AWS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: try_deploy_to_aws_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: try_deploy_to_aws_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: try_deploy_to_aws_production_cable
    migrations_paths: db/cable_migrate
